# run tmate on macos-13 gha runner

name: example

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.6", "3.7"]
    runs-on: macos-13
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -c 'import readline'